### ISSUE TITLE
File not found at servoy_jasperreports_commons.jar.jnlp

### ISSUE THREAD

**Issue by juanetec** [Servoy/servoy_jasperreports#4]
Hi,
installing the new servoy version 2022.03.1 and the last servoy_ jasperreports release I cannot find the file that the file servoy_jasperreports_commons.jar.jnlp describe (<jar href="/lib/org.apache.commons.lang3_3.12.0.jar" download="lazy" part="commons-lang" version="%%version%%"/> ).
I found that problem went I try to test it in a tomcat with the smartClient it shows that Error:

`JNLPException[category: Error de archivo de inicio : Exception: null : LaunchDesc: 
<jnlp codebase="http://localhost:8083/servoyServer/" href="servoy-client/plugins/servoy_jasperreports_commons.jar.jnlp" spec="1.0+">
  <information>
    <title>Servoy Client Plugins</title>
    <vendor>Servoy and Others</vendor>
  </information>
  <resources>
    <j2se version="1.6+"/>
    <jar download="eager" href="lib/org.apache.commons.lang3_3.12.0.jar" part="commons-lang" version="1654789680000"/>
    <package name="org.apache.commons.lang3.*" part="commons-lang" recursive="true"/>
    <jar download="eager" href="lib/commons-io.jar" part="commons-io" version="1654789678000"/>
    <package name="org.apache.commons.io.*" part="commons-io" recursive="true"/>
    <jar download="eager" href="lib/commons-collections.jar" part="commons-collections" version="1654789678000"/>
    <package name="org.apache.commons.collections4.*" part="commons-collections" recursive="true"/>
    <jar download="eager" href="plugins/jakarta-poi/commons-math3.jar" part="commons-math3" version="1654789666000"/>
    <package name="org.apache.commons.math3.*" part="commons-math3" recursive="true"/>
    <jar download="eager" href="plugins/jakarta-poi/jakarta-poi.jar" part="poi" version="1654789666000"/>
    <package name="org.apache.poi.*" part="poi" recursive="true"/>
    <jar download="eager" href="plugins/pdf_output/itext.jar" part="itext" version="1654789668000"/>
    <package name="com.lowagie.*" part="itext" recursive="true"/>
    <jar download="eager" href="plugins/jackson/jackson-annotations.jar" part="jackson-annotations" version="1654789666000"/>
    <package name="com.fasterxml.jackson.annotation.*" part="jackson-annotations" recursive="true"/>
    <jar download="eager" href="plugins/jackson/jackson-core.jar" part="jackson-core" version="1654789666000"/>
    <package name="com.fasterxml.jackson.core.*" part="jackson-core" recursive="true"/>
    <jar download="eager" href="plugins/jackson/jackson-databind.jar" part="jackson-databind" version="1654789666000"/>
    <package name="com.fasterxml.jackson.databind.*" part="jackson-databind" recursive="true"/>
  </resources>
  <component-desc/>
  <security>
    <all-permissions/>
  </security>
</jnlp> ]
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

What can I do? download that file from internet and put at the servoy lib folder?

Un Saludo

Juan Ramírez

**Comment by jcompagner** [comment]
are you signing yourself?

because then you really need to sign what is generated inside the war because else you are missing some files (or sign maybe the file directly in the developer/plugins dir)

**Comment by juanetec** [comment]
Yes, I sign it by myself. I sign with CodeSigner8.291 in the application server folder. It sign all jar file that are into beans, lib and plugins folders. This is the way what I have done always.
I don`t know to much about Java, but I am looking for that file lib/org.apache.commons.lang3_3.12.0.jar and cannot find it.
What do you say is: download that file from internet and put at the servoy lib folder or plugins folder, redirect the servoy_jasperreports_commons.jar.jnlp and sign this file?

Un Saludo
